#!/bin/sh
rm /tmp/reval*
REVALRC=~/.reval.vimrc
BACKUPRC=${REVALRC}.saved
[ -e $REVALRC ] && mv $REVALRC $BACKUPRC
reval
echo "let g:revallang = 'ruby'" > $REVALRC
reval
[ -e $BACKUPRC ] && mv $BACKUPRC $REVALRC
